require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ttamna' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'Firebase/Analytics'
  pod 'FBSDKLoginKit'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  target 'ttamnaTests' do
    inherit! :complete
    # Pods for testing
  end

    pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
    permissions_path = '../node_modules/react-native-permissions/ios'

    pod 'Permission-Camera', :path => "#{permissions_path}/Camera/Permission-Camera.podspec"
    pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways/Permission-LocationAlways.podspec"
    pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"
    pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary/Permission-PhotoLibrary.podspec"

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ttamna-tvOS' do
  # Pods for ttamna-tvOS

  target 'ttamna-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
